# https://github.com/marketplace/actions/easy-zip-files

name: Add zipped src/* to release on publish

on:
  release:
    types: [published]

# permissions:
#   contents: write

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: src
          recursive: false
          # dest: $GITHUB_ACTION_REPOSITORY-$GITHUB_REF_NAME.zip
          dest: release.zip
